#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Aditya Sharma

author: adityashrm21

# Short bio or description (displayed in the header)
description: Data Science | Artificial Intelligence | Machine Learning

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://scontent-sea1-1.xx.fbcdn.net/v/t31.0-8/16836275_1371837592866969_6245516334635420573_o.jpg?_nc_cat=0&oh=bf1da87e2af2e3ab5fd1fa75d487c584&oe=5C2C39DE

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: adityashrm21@gmail.com
  facebook:
  flickr:
  github: adityashrm21
  instagram:
  linkedin: adityashrm21/
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: adityashrm21
  stackoverflow: users/4316766/aditya-sharma
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: adityashrm21

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-57616981-2
# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://adityashrm21.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "https://adityashrm21.github.io"

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag
plugins:
  - jekyll-seo-tag

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

theme: jekyll-theme-cayman
